"""************************************************************************
Key-Binding Output
******************

This module's primary job is navigating the data generated by the
``data.KeyBindingData`` class and generating tables of key-binding data
plus the footnotes that go with them.

Secondary to that, this module contains knowledge about KeyBindingReport
output formats such as title, headings, key names and column
headings.  (Platform-specific key names and column headings that change
platform to platform, are in the ``platform`` module.)

Lastly, it has tests related to whether certain parts of the output are to
be included or not based on caller-passed flags and output formats.



Tables
******

Tables are rows and columns of data without formatting.  Specifically they
are lists of lists of strings, where each string contains the content of 1
table cell.  Formatting is left to to the caller, which uses formatting
tools such as ``lib.ascii_table``.



Footnotes
*********

Footnotes are lists of ``Footnote`` objects, each having enough data to
represent itself as a string in the desired format.  Having each
``Footnote`` object generate its representation is left to the caller.  The
lists of fully-populated Footnote objects are returned with the tables they
belong with.



Design
******

A.  There is a concept of a ``output`` module object.

    1.  It has:
        +   Current modifier-flag symbol; default:  'x'.
        +   Current comments-column width; default:  35.
        +   Minimum column count:  8  (used to pre-allocate arrays)
    2.  It can be asked:
        +   main_key_table
            +   Used by caller when output is to be in 1 table.
            +   returns content of gathered main-key binding data as a table
        +   main_key_tables (plural)
            +   Used by caller when output is to be in 1 table per key group.
            +   returns content of gathered main-key binding data as a table
        +   key_sequence_table
            +   Used by caller when there are multi-keypress key bindings in output.
            +   returns content of gathered key-sequence binding data as a table
    3.  It can be requested to change output objects as follows:
        +   Instantiation establishes the input data to be used for reporting.

B.  There is a concept of a ``Footnote`` object:  a container for a
    key-binding table footnote, able to represent itself as a formatted
    string.

    1.  It has:
        +   a reference to the key binding whose context it represents,
        +   the footnote number it was assigned,
        +   flag bits (bit-wise OR-ed data.FlagBits class enumerator values) containing
            what type of contexts were originally requested in the report, and
        +   the requested data format (affects its output representation when
            the requested format is reStructuredText).
    2.  It can be asked:
        +   default representation (str)
        +   formatted representation (str)
    3.  It can be requested to change:
        +   This only happens at instantiation time, based on the arguments
            passed.



Data Flow
*********

Key-binding input data, plus report flags, format, and last-used footnote
number) is passed directly to each of the primary API functions:

+   main_key_table
    +   Used by caller when output is to be in 1 table.
    +   returns content of gathered main-key binding data as a table
+   main_key_tables (plural)
    +   Used by caller when output is to be in 1 table per key group.
    +   returns content of gathered main-key binding data as a table
+   key_sequence_table
    +   Used by caller when there are multi-keypress key bindings in output.
    +   returns content of gathered key-sequence binding data as a table

Each of these functions returns 1 or more tuples, each of which contain:

- one table,
- the list of footnotes that go with it, if any, and
- the last-used footnote number.

This arms the caller with the data to generate any number of report
formats from that data.



@version  Current revision:  @(#) v1.0  22-Apr-2026 15:54
@version  1.0  22-Apr-2026 15:54  vw  - Created.
***************************************************************************"""

from datetime import datetime
from typing import List, Tuple
from ..lib.debug import DebugBits, is_debugging
from ..lib import ascii_table
from ..lib import rst_utils
from . import platform
from . import core
from . import data
from . import key_binding


# *************************************************************************
# Configuration
# *************************************************************************



# *************************************************************************
# Constants
# *************************************************************************

min_column_count = 8



# *************************************************************************
# Classes
# *************************************************************************

class Footnote:
    """ Containers for key-binding table footnotes """
    __slots__ = ['key_binding', 'number', 'flags', 'format']

    def __init__(
            self,
            key_binding: key_binding.ReportKeyBinding,
            number     : int,
            flags      : data.FlagBits,
            format     : ascii_table.Format
            ):
        self.key_binding = key_binding
        self.number      = number
        self.flags       = flags
        self.format      = format

    def __str__(self) -> str:
        return self.formatted()

    def formatted_reference(self) -> str:
        """ Footnote reference appropriate for ``format`` """
        if self.format == ascii_table.Format.RESTRUCTUREDTEXT:
            result = f'[{self.number}]_'
        else:
            result = f'({self.number})'

        return result

    def formatted(self) -> str:
        """ Footnote content appropriate for ``format`` """
        result = ''
        binding = self.key_binding
        context = binding.smart_context()

        if context:
            raw          = bool(self.flags & data.FlagBits.INCLUDE_UNTRANSLATED_CONTEXTS)
            natural_lang = bool(self.flags & data.FlagBits.INCLUDE_NATURAL_LANGUAGE_CONTEXTS)

            footnote_str = context.formatted(
                    2,
                    raw=raw,
                    natural_language=natural_lang,
                    minimal=True
                    )

            if self.format == ascii_table.Format.RESTRUCTUREDTEXT:
                # .. [1] context for :kbd:`Alt-1`:
                # .. code-block:: json
                #
                #     "context": [
                #       { "key": "group_has_multiselect", "operator": "equal", "operand": true, "match_all": false }
                #     ]
                rst_keypress_list = binding.keypresses_human_friendly_rst_list()
                rst_keypress_str = ', '.join(rst_keypress_list)
                cmd_func_repr = binding.command_with_args_rst()
                result = (
                        f'.. [{self.number}] Context for {rst_keypress_str}:  {cmd_func_repr}\n'
                        f'.. code-block:: json\n\n{footnote_str}'
                        )
            else:
                result = f'({self.number}):\n{footnote_str}'

        return result


class TablePackage:
    """Table, Footnotes, Last Footnote Number, and optional Table Name"""
    __slots__ = ['fmt', 'flags', 'table', 'footnotes', 'last_footnote_number']

    def __init__(self,
            fmt              : ascii_table.Format,
            flags            : data.FlagBits,
            prev_footnote_num: int = 0,
            ):
        self.fmt = fmt
        self.flags = flags
        self.table: List[List[str]] = []
        self.footnotes: List[Footnote] = []
        self.last_footnote_number = prev_footnote_num

    def append_heading_row(self):
        if include_windows_key(self.flags):
            effective_min_col_count = min_column_count

            row = [
                    platform.cfg_key_col_heading,
                    platform.cmd_col_heading,
                    platform.alt_col_heading,
                    platform.ctrl_col_heading,
                    platform.shift_col_heading,
                    platform.cfg_context_col_heading,
                    platform.cfg_command_col_heading,
                    platform.cfg_args_col_heading,
                    ]
        else:
            effective_min_col_count = min_column_count - 1

            row = [
                    platform.cfg_key_col_heading,
                    platform.alt_col_heading,
                    platform.ctrl_col_heading,
                    platform.shift_col_heading,
                    platform.cfg_context_col_heading,
                    platform.cfg_command_col_heading,
                    platform.cfg_args_col_heading,
                    ]

        if len(row) != effective_min_col_count:
            raise AssertionError('output.main_key_table():  length of `row` and `min_col_count` must match.')

        if self.flags & data.FlagBits.ADD_SOURCE_COLUMN:
            row.append('Source')
        if self.flags & data.FlagBits.ADD_COMMENTS_COLUMN:
            row.append('Comments')

        self.table.append(row)

    def append_rows_for_one_keypress(self,
            main_key_name  : str,
            binding_list   : List[key_binding.ReportKeyBinding],
            is_2nd_keypress: bool = False,
            ):
        """
        Append rows for `binding_list`.

        :param main_key_name:    Name of key to be in first column of table
        :param binding_list:     List of bindings for keypress
        :param is_2nd_keypress:  Is `main_key_name` the 2nd keypress in a
                                   keypress sequence?  (This is True when a
                                   table is being generated for a keypress
                                   sequence (e.g. for ["ctrl+k", "ctrl+..."]).)
        """
        if not binding_list:
            raise AssertionError(f'`binding_list` must be a list of 1 or more ReportKeyBinding objects.  Got {binding_list} instead.')

        # -----------------------------------------------------------------
        # Heading row?
        # -----------------------------------------------------------------
        if len(self.table) == 0:
            self.append_heading_row()

        if binding_list:
            # -------------------------------------------------------------
            # Process binding_list.
            # -------------------------------------------------------------
            include_win_key = include_windows_key(self.flags)

            # Compute `mod_key_flags_tpl`.
            first_binding = binding_list[0]

            if is_2nd_keypress:
                keypr = first_binding.keypresses[1]
            else:
                keypr = first_binding.keypresses[0]

            mod_key_flags_tpl = keypr.modifier_flag_characters(modifier_flag_symbol)

            for binding in binding_list:
                # ---------------------------------------------------------
                # Keys
                # ---------------------------------------------------------
                if self.fmt == ascii_table.Format.RESTRUCTUREDTEXT:
                    tbl_key_name = rst_utils.rst_escaped_for_table(main_key_name)
                else:
                    tbl_key_name = main_key_name

                row = [tbl_key_name]                  # 'f5'
                if include_win_key:
                    row.append(mod_key_flags_tpl[0])  # Windows/Command Key
                row.append(mod_key_flags_tpl[1])      # Alt
                row.append(mod_key_flags_tpl[2])      # Ctrl
                row.append(mod_key_flags_tpl[3])      # Shift

                # ---------------------------------------------------------
                # Context
                # ---------------------------------------------------------
                if binding.has_context():
                    if self.flags & data.FlagBits.ANY_CONTEXT_REQUESTED:
                        # User requested detailed context information
                        self.last_footnote_number += 1
                        footnote = Footnote(binding, self.last_footnote_number, self.flags, self.fmt)
                        self.footnotes.append(footnote)
                        context_ref = footnote.formatted_reference()
                    else:
                        context_ref = 'x'
                else:
                    context_ref = ' '

                row.append(context_ref)

                # ---------------------------------------------------------
                # Command
                # ---------------------------------------------------------
                row.append(binding.command())

                # ---------------------------------------------------------
                # Args
                # ---------------------------------------------------------
                if binding.has_args():
                    if self.fmt == ascii_table.Format.RESTRUCTUREDTEXT:
                        args_str = binding.args_rst()
                    else:
                        args_str = binding.args_json()
                else:
                    args_str = ' '

                row.append(args_str)

                # ---------------------------------------------------------
                # Remaining optional columns.
                # ---------------------------------------------------------
                if self.flags & data.FlagBits.ADD_SOURCE_COLUMN:
                    row.append(binding.source())
                if self.flags & data.FlagBits.ADD_COMMENTS_COLUMN:
                    row.append(' ' * comments_column_width)

                self.table.append(row)

    def append_empty_row(self,
            main_key_name: str,
            modifier_code: int,
            ):
        """
        Append empty rows for `main_key_name`:  there is no associated binding.

        :param main_key_name:    Name of key to be in first column of table
        :param binding_list:     List of bindings for keypress
        :param is_2nd_keypress:  Is `main_key_name` the 2nd keypress in a
                                   keypress sequence?  (This is True when a
                                   table is being generated for a keypress
                                   sequence (e.g. for ["ctrl+k", "ctrl+..."]).)
        """
        include_win_key = include_windows_key(self.flags)
        space = ' '
        mod_key_flags_tpl = key_binding.modifier_flag_characters(modifier_code, modifier_flag_symbol)

        # -----------------------------------------------------------------
        # Heading row?
        # -----------------------------------------------------------------
        if len(self.table) == 0:
            self.append_heading_row()

        # -----------------------------------------------------------------
        # Keys
        # -----------------------------------------------------------------
        if self.fmt == ascii_table.Format.RESTRUCTUREDTEXT:
            tbl_key_name = rst_utils.rst_escaped_for_table(main_key_name)
        else:
            tbl_key_name = main_key_name

        row = [tbl_key_name]                  # 'f5'

        if include_win_key:
            row.append(mod_key_flags_tpl[0])  # Command)

        row.append(mod_key_flags_tpl[1])      # Alt
        row.append(mod_key_flags_tpl[2])      # Ctrl
        row.append(mod_key_flags_tpl[3])      # Shift
        row.append(space)                     # Context (not bound to any commands)
        row.append(space)                     # Command (not bound to any commands)
        row.append(space)                     # Args    (not bound to any commands)

        # -----------------------------------------------------------------
        # Optional columns.
        # -----------------------------------------------------------------
        if self.flags & data.FlagBits.ADD_SOURCE_COLUMN:
            row.append(space)
        if self.flags & data.FlagBits.ADD_COMMENTS_COLUMN:
            row.append(' ' * comments_column_width)

        self.table.append(row)



# *************************************************************************
# Data
# *************************************************************************

modifier_flag_symbol = 'x'
comments_column_width = 35


def set_modifier_flag_symbol(sym: str):
    """ Set modifier-applies symbol to first character in ``sym``. """
    if len(sym) == 0:
        raise AssertionError('set_modifier_flag_symbol:  `sym` must be at least 1 character long.  Got empty string.')
    global modifier_flag_symbol
    modifier_flag_symbol = sym[0]


def set_comments_column_width(width: int):
    """ Set new comments-column width, clamped to positive values. """
    global comments_column_width
    comments_column_width = max(1, width)



# *************************************************************************
# Utilities
# *************************************************************************

def report_heading(title: str, note: str = '') -> str:
    timestamp = datetime.now().strftime(core.setting__timestamp_strftime_format)
    under_over_line = '*' * len(title)
    exe_platform = platform.execution_platform_name
    sim_platform = platform.platform_name
    parts = []
    parts.append('')
    parts.append(under_over_line)
    parts.append(title)
    parts.append(under_over_line)
    parts.append('')

    if sim_platform == exe_platform:
        parts.append(f'As of   :  {timestamp}')
        parts.append(f'Platform:  {exe_platform}')
    else:
        parts.append(f'As of    :  {timestamp}')
        parts.append(f'Platform :  {exe_platform}')
        parts.append(f'Simulated:  {sim_platform}')

    if note:
        parts.append('')
        parts.append('Note:')
        parts.append('    ' + note)

    return '\n'.join(parts)


def section_heading(title: str, underline_char: str) ->str:
    underline = underline_char * len(title)
    parts = []

    if underline_char == '*':
        blank_line_above_count = 3
    elif underline_char == '=':
        blank_line_above_count = 2
    elif underline_char == '-':
        blank_line_above_count = 1
    elif underline_char == '~':
        blank_line_above_count = 1
    else:
        # Not recognized, so we will assume 3.
        blank_line_above_count = 3

    for i in range(blank_line_above_count):
        parts.append('')

    parts.append(title)
    parts.append(underline)

    return '\n'.join(parts)


def include_windows_key(flags: data.FlagBits):
    return ((
               platform.is_osx()
            or bool(flags & data.FlagBits.INCLUDE_WINDOWS_KEY)
            ))



# *************************************************************************
# Function Definitions
# *************************************************************************

def main_key_table(
        key_data         : data.KeyBindingData,
        flags            : data.FlagBits,
        fmt              : ascii_table.Format,
        prev_footnote_num: int = 0
        ) -> TablePackage:
    r"""
    Generate and return main-key table.

    Input Data Structure:
    ---------------------
    by_main_key_dict
        "a": [  <-- binding_lists_by_mod_code                          Mod Code
                None,   # binding list for unmodified 'a' key           0x0
                None,   # binding list for [Shift-a]                    0x1
        _____/  [...],  # binding list for [Ctrl-a]                     0x2
       |     \  [...],  # binding list for [Ctrl-Shift-a]               0x3
       |        None,   # binding list for [Alt-a]                      0x4
       |        None,   # binding list for [Alt-Shift-a]                0x5
     binding    None,   # binding list for [Alt-Ctrl-a]                 0x6
     lists      None,   # binding list for [Alt-Ctrl-Shift-a]           0x7
       |        None,   # binding list for [Command-a]                  0x8
       |        None,   # binding list for [Command-Shift-a]            0x9
       |_____/  [...],  # binding list for [Command-Ctrl-a]             0xA
             \  [...],  # binding list for [Command-Ctrl-Shift-a]       0xB
                None,   # binding list for [Command-Alt-a]              0xC
                None,   # binding list for [Command-Alt-Shift-a]        0xD
                None,   # binding list for [Command-Alt-Ctrl-a]         0xE
                None,   # binding list for [Command-Alt-Ctrl-Shift-a]   0xF
            ]

    Possible Columns:
    -----------------
    Key W A C S Command  Args  Context  Source  Comments

    :param flags:              OR-ed combination of data.FlagBits bits
    :param fmt:                needed to instantiate Footnote objects
    :param prev_footnote_num:  one-based last-footnote number;
                                 0 = first footnote has not yet been generated.

    :return:  tuple:  table, footnotes, last_footnote_num
    """
    debugging = is_debugging(DebugBits.OUTPUT)
    if debugging:
        print('In output.main_key_table()...')
        print(f'  {flags = :#011_b}')

    include_unbound_keypresses = flags & data.FlagBits.ANY_UNBOUND_KEYPRESSES
    include_no_bindings = flags & data.FlagBits.INCLUDE_UNBOUND_KEYPRESSES_ONLY
    include_win_key = include_windows_key(flags)
    by_main_key_dict = key_data.mdictByMainKey
    key_groups_requested = bool(key_data.key_groups) # is not None and len() > 0.
    tbl_pkg = TablePackage(fmt, flags, prev_footnote_num)

    for main_key_name in by_main_key_dict:
        binding_lists_by_mod_code = by_main_key_dict[main_key_name]
        has_no_key_bindings = not any(binding_lists_by_mod_code)

        # Do not iterate through empty binding lists when none have bindings,
        # unless `key_groups` was part of the user request, in which case
        # the user wants to see the keys with no bindings.
        if has_no_key_bindings and not key_groups_requested:
            continue

        if include_unbound_keypresses:
            # Include unbound keypresses.
            num_to_process = 16 if include_win_key else 8

            for modifier_code in range(num_to_process):
                binding_list = binding_lists_by_mod_code[modifier_code]

                if binding_list:
                    if include_no_bindings:
                        pass
                        # Caller requested INCLUDE_UNBOUND_KEYPRESSES_ONLY, so we
                        # don't include this set of bindings---only empty slots.
                    else:
                        tbl_pkg.append_rows_for_one_keypress(main_key_name, binding_list)
                else:
                    tbl_pkg.append_empty_row(main_key_name, modifier_code)
        else:
            # Do not include unbound keypresses.
            for modifier_code, binding_list in enumerate(binding_lists_by_mod_code):
                if not binding_list:
                    continue

                # Here we know ``binding_list`` contains bindings.
                tbl_pkg.append_rows_for_one_keypress(main_key_name, binding_list)

    return tbl_pkg


def main_key_tables(
        key_data         : data.KeyBindingData,
        flags            : data.FlagBits,
        fmt              : ascii_table.Format,
        prev_footnote_num: int = 0
        ) -> List[  Tuple[int, TablePackage]  ]:
    r"""
    Like ``main_key_table()`` only it creates a LIST of main-key tables,
    1 table per key-group occurring in the data.

    The data structure inside ``data.mdictByMainKey`` is already
    ordered in key-group order.  However, the logic below is simplified
    if we manager our flow of control directly from the key-group lists.

    Input Data Structure:
    ---------------------
    by_main_key_dict
        "a": [  <-- binding_lists_by_mod_code                          Mod Code
                None,   # binding list for unmodified 'a' key           0x0
                None,   # binding list for [Shift-a]                    0x1
        _____/  [...],  # binding list for [Ctrl-a]                     0x2
       |     \  [...],  # binding list for [Ctrl-Shift-a]               0x3
       |        None,   # binding list for [Alt-a]                      0x4
       |        None,   # binding list for [Alt-Shift-a]                0x5
     binding    None,   # binding list for [Alt-Ctrl-a]                 0x6
     lists      None,   # binding list for [Alt-Ctrl-Shift-a]           0x7
       |        None,   # binding list for [Command-a]                  0x8
       |        None,   # binding list for [Command-Shift-a]            0x9
       |_____/  [...],  # binding list for [Command-Ctrl-a]             0xA
             \  [...],  # binding list for [Command-Ctrl-Shift-a]       0xB
                None,   # binding list for [Command-Alt-a]              0xC
                None,   # binding list for [Command-Alt-Shift-a]        0xD
                None,   # binding list for [Command-Alt-Ctrl-a]         0xE
                None,   # binding list for [Command-Alt-Ctrl-Shift-a]   0xF
            ]

    Possible Columns:
    -----------------
    Key W A C S Command  Args  Context  Source  Comments

    :param flags:              OR-ed combination of data.FlagBits bits
    :param fmt:                needed to instantiate Footnote objects
    :param prev_footnote_num:  one-based last-footnote number;
                                 0 = first footnote has not yet been generated.

    :return:  tuple:  table, footnotes, last_footnote_num
    """
    debugging = is_debugging(DebugBits.OUTPUT)
    if debugging:
        print('In output.main_key_tables()...')
        print(f'  {flags = :#011_b}')

    include_unbound_keypresses = flags & data.FlagBits.ANY_UNBOUND_KEYPRESSES
    include_no_bindings = flags & data.FlagBits.INCLUDE_UNBOUND_KEYPRESSES_ONLY
    include_win_key = include_windows_key(flags)
    footnote_num = prev_footnote_num
    by_main_key_dict = key_data.mdictByMainKey
    key_groups_requested = bool(key_data.key_groups) # is not None and len() > 0.

    tbl_pkg_list: List[Tuple[int, TablePackage]] = []

    for key_group_idx, key_group_list in enumerate(data.key_name_groups):
        # Start new table.  Don't add headings yet until
        # we know there is going to be some content.
        tbl_pkg = TablePackage(fmt, flags, footnote_num)

        for main_key_name in key_group_list:
            # We know ``main_key_name in by_main_key_dict`` because
            # ``key_group_list`` was used to build the empty version of
            # it at the beginning of the data gathering.
            binding_lists_by_mod_code = by_main_key_dict[main_key_name]
            has_no_key_bindings = not any(binding_lists_by_mod_code)

            # Do not iterate through empty binding lists when none have bindings,
            # unless `key_groups` was part of the user request, in which case
            # the user wants to see the keys with no bindings.
            if has_no_key_bindings and not key_groups_requested:
                continue

            if include_unbound_keypresses:
                # Include unbound keypresses.
                num_to_process = 16 if include_win_key else 8

                for modifier_code in range(num_to_process):
                    binding_list = binding_lists_by_mod_code[modifier_code]

                    if binding_list:
                        # Now we know there is content.
                        if include_no_bindings:
                            pass
                            # Caller requested INCLUDE_UNBOUND_KEYPRESSES_ONLY, so we
                            # don't include this set of bindings---only empty slots.
                        else:
                            # Heading not added yet?  Add it now.
                            tbl_pkg.append_rows_for_one_keypress(main_key_name, binding_list)
                    else:
                        tbl_pkg.append_empty_row(main_key_name, modifier_code)
            else:
                # Do not include unbound keypresses.
                for modifier_code, binding_list in enumerate(binding_lists_by_mod_code):
                    if not binding_list:
                        continue

                    # Here we know ``binding_list`` contains bindings.
                    # Heading not added yet?  Add it now.
                    tbl_pkg.append_rows_for_one_keypress(main_key_name, binding_list)

        # We've reached the end of a key group.
        tbl_pkg_list.append( (key_group_idx, tbl_pkg) )
        footnote_num = tbl_pkg.last_footnote_number

    return tbl_pkg_list


def key_seq_tables(
        key_data         : data.KeyBindingData,
        fmt              : ascii_table.Format,
        flags            : data.FlagBits,
        prev_footnote_num: int = 0
        ) -> List[  Tuple[str, TablePackage]  ]:
    """
    Generate and return:

    - List of tuples, one per UNIQUE LEADING KEYPRESS, each containing:

        - leading keypress string (e.g. "ctrl+k"; can be used to form title for table)
        - table of key bindings by secondary key,
        - footnotes,
        - last_used_footnote_num (in case caller needs to append more output
          with footnotes).

    Each table generated is much like Main-Key Table except the
    `FlagBits.INCLUDE_UNBOUND_KEYPRESSES` flag has no meaning
    in this report.  Only the bindings actually in the data are reported.

    Input Data Structure:
    ---------------------
    by_key_seq_dict
        ("ctrl+k", "ctrl+up"):
            [ <-- binding_list
                ReportKeyBinding object,
                ReportKeyBinding object,
                ReportKeyBinding object,
                ...
            ]

    Possible Columns:
    -----------------
    Key W A C S Command  Args  Context  Source  Comments

    :param flags:              OR-ed combination of data.FlagBits bits
    :param fmt:                needed to instantiate Footnote objects
    :param prev_footnote_num:  one-based last-footnote number;
                                 0 = first footnote has not yet been generated.

    :return:  List[tuple] each tuple containing:
                (lead_keypr_str, table, footnotes, last_footnote_num)
    """
    debugging = is_debugging(DebugBits.OUTPUT)
    if debugging:
        print('In output.key_seq_tables()...')
        print(f'  {flags = :#011_b}')

    by_key_seq_dict = key_data.mdictByKeySquence

    # -----------------------------------------------------------------
    # Build set of leading keypresses.
    # -----------------------------------------------------------------
    lead_keypr_str_set = set()

    for keypress_tuple_bep in by_key_seq_dict:
        leading_keypress_str = keypress_tuple_bep[0]
        lead_keypr_str_set.add(leading_keypress_str)

    # `lead_keypr_str_set` now contains the list of unique leading
    # keypress strings.  Example:
    #
    # - "ctrl+j"
    # - "ctrl+k"
    # - "alt+k"
    # - "ctrl+t"

    # -----------------------------------------------------------------
    # Create top-level list.
    # -----------------------------------------------------------------
    tbl_pkg_list: List[  Tuple[str, TablePackage]  ] = []

    if len(lead_keypr_str_set) > 0:
        footnote_num = prev_footnote_num

        for lead_keypr_str in sorted(lead_keypr_str_set):
            # Generate new table and new footnotes list for each
            # unique leading keypress.
            tbl_pkg = TablePackage(fmt, flags, prev_footnote_num)

            # ---------------------------------------------------------
            # Pass through `by_key_seq_dict` selecting only bindings
            # whose leading keypress matches `lead_keypr_str`.
            # ---------------------------------------------------------
            # `sorted()` doesn't do well for `by_key_seq_dict` because
            # it mixes the key groups up.  So we take another approach:
            # by key group in sequence.
            # ---------------------------------------------------------
            # Extract keypress_tuples by `lead_keypr_str` into a list.
            sortable_list = []
            for keypress_tuple_bep in by_key_seq_dict:
                leading_keypress_str = keypress_tuple_bep[0]
                if leading_keypress_str == lead_keypr_str:
                    sortable_list.append(keypress_tuple_bep)

            # Sort list by special sort routine that uses the key
            # groups and sorts by:
            # - secondary-keypress main key
            # - mod_code
            sorted_tuple_list = data.sort_keypress_tuple_list_by_secondary_key(sortable_list)

            # Finally, iterate through sorted list, pull and build
            # tables by that sequence.
            for scored_keypress_tuple_bep in sorted_tuple_list:
                keypress_tuple = scored_keypress_tuple_bep.keypress_tuple
                binding_list = by_key_seq_dict[keypress_tuple]

                tbl_pkg.append_rows_for_one_keypress(
                        scored_keypress_tuple_bep.second_main_key_name,
                        binding_list,
                        True
                        )

            tbl_pkg_list.append((lead_keypr_str, tbl_pkg))

    return tbl_pkg_list

